import { useState, type ChangeEvent } from "react";
import { Alert, Button } from "../components/ui";
import { services } from "../services/app-services";
import type { BackupEnvelopeV1 } from "../schemas/backup";

type Preview = { snapshot: BackupEnvelopeV1; expectedRevision: number; currentCounts: Record<string, number>; restoredCounts: Record<string, number>; outsidePackReferences: number };
export function DataSettingsPage() {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [preview, setPreview] = useState<Preview>(); const [confirmed, setConfirmed] = useState(false);
  async function exportData() { setBusy(true); setError(""); try { const json = await services.exportBackup(); const blob = new Blob([json], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); const stamp = new Date().toISOString().replace(/[-:]/g, "").replace("T", "-").slice(0, 15); link.href = url; link.download = `exam-trainer-backup-${stamp}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url)); setMessage("バックアップを作成しました。"); } catch { setError("バックアップを作成できませんでした。"); } finally { setBusy(false); } }
  async function chooseFile(event: ChangeEvent<HTMLInputElement>) { setPreview(undefined); setConfirmed(false); setMessage(""); setError(""); const file = event.target.files?.[0]; if (file === undefined) return; try { setPreview(await services.previewBackup(await file.text())); } catch { setError("バックアップを検証できませんでした。版と内容を確認してください。"); } }
  async function restore() { if (preview === undefined || !confirmed) return; setBusy(true); setError(""); try { await services.repository.replaceAll(preview.snapshot, preview.expectedRevision); setMessage("学習データをすべて置き換えました。"); setPreview(undefined); setConfirmed(false); } catch { setError("復元できませんでした。既存データは変更されていません。"); } finally { setBusy(false); } }
  return <section className="narrow"><p className="eyebrow">DATA</p><h2>データ管理</h2><Alert severity="warning" title="端末のデータ削除に備えてください">学習履歴はIndexedDBに保存されます。定期的なバックアップを推奨します。</Alert>{error && <Alert severity="error" title={error} />}{message && <Alert severity="success" title={message} />}<section className="panel"><h3>バックアップ</h3><p>回答履歴、お気に入り、復習状態、模擬試験、設定をJSONへ出力します。</p><Button className="primary" busy={busy} onClick={() => void exportData()}>JSONをダウンロード</Button></section><section className="panel"><h3>復元</h3><label className="input-stack"><span>バックアップファイル</span><input type="file" accept="application/json,.json" onChange={(event) => void chooseFile(event)} /></label>{preview && <div className="preview"><h4>置換内容の確認</h4><div className="table-wrap"><table><thead><tr><th>対象</th><th>現在</th><th>復元後</th></tr></thead><tbody><tr><th>回答履歴</th><td>{preview.currentCounts.attempts}</td><td>{preview.restoredCounts.attempts}</td></tr><tr><th>お気に入り</th><td>{preview.currentCounts.bookmarks}</td><td>{preview.restoredCounts.bookmarks}</td></tr><tr><th>模擬試験</th><td>{preview.currentCounts.examSessions}</td><td>{preview.restoredCounts.examSessions}</td></tr><tr><th>設定</th><td>{preview.currentCounts.settings}</td><td>{preview.restoredCounts.settings}</td></tr></tbody></table></div>{preview.outsidePackReferences > 0 && <Alert severity="warning" title="現在のPackにない参照があります">{preview.outsidePackReferences}件の履歴は保持されますが、現在の成績集計には含まれません。</Alert>}<label className="choice"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /><span>現在の学習データが全置換されることを確認しました</span></label><Button className="danger" busy={busy} disabled={!confirmed} onClick={() => void restore()}>現在の学習データを置き換える</Button></div>}</section></section>;
}
