import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import type { ExamCatalogEntry } from "../schemas/exam-pack";
import type { DomainAllocation, ExamSession, InProgressExamSession } from "../types/learning-data";
import type { ExamPackIndex } from "../types/exam-pack";
import { services } from "../services/app-services";
import { Alert, Button, Loading, QuestionInput } from "../components/ui";
import { storePracticeSession } from "../services/practice-session";

function formatTime(milliseconds: number): string {
  const seconds = Math.max(0, Math.ceil(milliseconds / 1000));
  const hours = Math.floor(seconds / 3600); const minutes = Math.floor((seconds % 3600) / 60); const rest = seconds % 60;
  return hours > 0 ? `${hours}:${String(minutes).padStart(2, "0")}:${String(rest).padStart(2, "0")}` : `${minutes}:${String(rest).padStart(2, "0")}`;
}

export function MockSetupPage() {
  const { examId = "" } = useParams(); const navigate = useNavigate(); const [entry, setEntry] = useState<ExamCatalogEntry>(); const [count, setCount] = useState(1); const [minutes, setMinutes] = useState(1); const [allocations, setAllocations] = useState<readonly DomainAllocation[]>([]); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const seed = useMemo(() => crypto.getRandomValues(new Uint32Array(1))[0] ?? 0, []);
  useEffect(() => { void services.catalog.list().then((entries) => { const found = entries.find((item) => item.examId === examId); if (found) { setEntry(found); setCount(found.questionCount); setMinutes(found.durationMinutes); } }); }, [examId]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const preview = await services.previewMock(examId, count, minutes, seed); if (!preview.ok) { setError(preview.error.code === "insufficient-total" ? `必要${preview.error.required}問に対し、利用可能${preview.error.available}問です（${preview.error.shortage}問不足）。` : "問題数と時間を範囲内の整数で指定してください。"); return; } if (preview.value.redistributed && !confirmed) { setAllocations(preview.value.domainAllocations); setError("分野の問題不足により配分を変更します。内容を確認してください。"); return; } const session = await services.createMock(examId, count, minutes, seed); navigate(`/exams/${examId}/mock/${session.id}`); } catch { setError("模擬試験を開始できませんでした。未完了の試験がないか確認してください。"); } finally { setBusy(false); } }
  if (entry === undefined) return <Loading />;
  return <section className="narrow"><Link className="back" to={`/exams/${examId}`}>← 試験ホーム</Link><p className="eyebrow">MOCK EXAM</p><h2>模擬試験を設定</h2><p>Pack上限: {entry.questionCount}問 / {entry.durationMinutes}分。現在利用できる問題は{entry.availableQuestionCount}問です。</p>{error && <Alert severity="error" title={error} />}<form className="panel form" onSubmit={(event) => void submit(event)}><label><span>問題数</span><input type="number" min="1" max={entry.questionCount} step="1" value={count} onChange={(event) => { setCount(event.target.valueAsNumber); setConfirmed(false); setAllocations([]); }} /></label><label><span>制限時間（分）</span><input type="number" min="1" max={entry.durationMinutes} step="1" value={minutes} onChange={(event) => { setMinutes(event.target.valueAsNumber); setConfirmed(false); }} /></label>{allocations.length > 0 && <div className="table-wrap"><table><caption>変更後の分野配分</caption><thead><tr><th>分野</th><th>当初</th><th>実数</th><th>差</th></tr></thead><tbody>{allocations.map((row) => <tr key={row.domainId}><th>{row.domainId}</th><td>{row.initialCount}</td><td>{row.actualCount}</td><td>{row.difference > 0 ? `+${row.difference}` : row.difference}</td></tr>)}</tbody></table><label className="choice"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /><span>配分を確認しました</span></label></div>}<Button className="primary" busy={busy}>模擬試験を始める</Button></form></section>;
}

export function MockExamPage() {
  const { examId = "", sessionId = "" } = useParams(); const navigate = useNavigate(); const [index, setIndex] = useState<ExamPackIndex>(); const [session, setSession] = useState<ExamSession>(); const [draft, setDraft] = useState<readonly string[]>([]); const [remaining, setRemaining] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void Promise.all([services.catalog.load(examId), services.repository.getExamSession(sessionId)]).then(([pack, saved]) => { setIndex(pack); setSession(saved); if (saved?.status === "completed") navigate(`/exams/${examId}/mock/${sessionId}/result`, { replace: true }); }); }, [examId, navigate, sessionId]);
  useEffect(() => { if (session?.status !== "in-progress") return; const tick = () => setRemaining(new Date(session.deadline).valueOf() - Date.now()); tick(); const timer = window.setInterval(tick, 1000); return () => window.clearInterval(timer); }, [session]);
  useEffect(() => { if (remaining > 0 || session?.status !== "in-progress" || index === undefined || busy) return; setBusy(true); void services.repository.submitExam(index, session.id, session.revision, "deadline").then(() => navigate(`/exams/${examId}/mock/${session.id}/result`, { replace: true })).catch(() => setError("自動提出できませんでした。再試行してください。")).finally(() => setBusy(false)); }, [busy, examId, index, navigate, remaining, session]);
  if (index === undefined || session === undefined) return <Loading />; if (session.status !== "in-progress") return <Loading />;
  const questionId = session.questionIds[session.currentIndex]; if (questionId === undefined) return <Alert severity="error" title="問題が見つかりません" />; const question = index.questionById.get(questionId); if (question === undefined) return <Alert severity="error" title="問題が見つかりません" />;
  const activeSession: InProgressExamSession = session; const activeIndex = index; const activeQuestionId = questionId;
  const value = draft.length > 0 ? draft : (activeSession.answers[activeQuestionId] ?? []); const flagged = activeSession.flaggedQuestionIds.includes(activeQuestionId);
  async function persist(patch: Partial<InProgressExamSession>) { setBusy(true); setError(""); try { const now = new Date().toISOString(); const saved = await services.repository.saveExamSession({ ...activeSession, ...patch, updatedAt: now }, activeSession.revision); setSession(saved); setDraft([]); } catch { setError("変更を保存できませんでした。入力を保持しています。"); } finally { setBusy(false); } }
  async function move(position: number) { await persist({ answers: { ...activeSession.answers, [activeQuestionId]: [...value] }, currentIndex: position }); }
  async function submit() { setBusy(true); try { const saved = await services.repository.saveExamSession({ ...activeSession, answers: { ...activeSession.answers, [activeQuestionId]: [...value] }, updatedAt: new Date().toISOString() }, activeSession.revision); await services.repository.submitExam(activeIndex, saved.id, saved.revision, "manual"); navigate(`/exams/${examId}/mock/${activeSession.id}/result`); } catch { setError("提出できませんでした。保存済み状態から再試行できます。"); setBusy(false); } }
  return <section><header className="mock-bar"><strong>問題 {activeSession.currentIndex + 1} / {activeSession.questionIds.length}</strong><span className={remaining < 60_000 ? "timer urgent" : "timer"} aria-label={`残り時間 ${formatTime(remaining)}`}>{formatTime(remaining)}</span><span>回答済み {Object.keys(activeSession.answers).length}</span></header>{error && <Alert severity="error" title={error} />}<div className="question-layout"><article className="panel"><p className="eyebrow">{question.domainId} · 難易度 {question.difficulty}</p><h2>{question.question}</h2><QuestionInput question={question} value={value} disabled={busy} onChange={setDraft} /><Button className="secondary" busy={busy} onClick={() => void persist({ answers: { ...activeSession.answers, [activeQuestionId]: [...value] } })}>回答を保存</Button></article><aside className="panel"><h3>問題ナビゲーション</h3><div className="number-grid">{activeSession.questionIds.map((id, position) => <button type="button" className={activeSession.answers[id] ? "answered" : ""} aria-current={position === activeSession.currentIndex ? "step" : undefined} key={id} onClick={() => void move(position)}>{position + 1}</button>)}</div><Button className="ghost" busy={busy} onClick={() => void persist({ flaggedQuestionIds: flagged ? activeSession.flaggedQuestionIds.filter((id) => id !== activeQuestionId) : [...activeSession.flaggedQuestionIds, activeQuestionId] })}>{flagged ? "⚑ 見直しを解除" : "⚐ 見直しに追加"}</Button><Button className="danger" busy={busy} onClick={() => void submit()}>模擬試験を提出</Button></aside></div></section>;
}

export function MockResultPage() {
  const { examId = "", sessionId = "" } = useParams(); const navigate = useNavigate(); const [session, setSession] = useState<ExamSession>();
  useEffect(() => { void services.repository.getExamSession(sessionId).then(setSession); }, [sessionId]);
  if (session?.status !== "completed") return <Loading />; const result = session.result;
  return <section><p className="eyebrow">RESULT</p><h2>模擬試験の結果</h2><div className="score"><strong>{result.percentage.toFixed(1)}%</strong><span>{result.totalCount}問中 {result.correctCount}問正解 / 回答 {result.answeredCount}問</span></div><div className="panel table-wrap"><table><caption>分野別結果</caption><thead><tr><th>分野</th><th>正解</th><th>問題数</th><th>正答率</th></tr></thead><tbody>{result.domainResults.map((row) => <tr key={row.domainId}><th>{row.domainId}</th><td>{row.correctCount}</td><td>{row.totalCount}</td><td>{row.percentage.toFixed(1)}%</td></tr>)}</tbody></table></div><div className="result-lists"><section><h3>誤答</h3><p>{result.incorrectQuestionIds.join(", ") || "なし"}</p></section><section><h3>未回答</h3><p>{result.unansweredQuestionIds.join(", ") || "なし"}</p></section><section><h3>見直し対象</h3><p>{result.flaggedQuestionIds.join(", ") || "なし"}</p></section></div><div className="pager">{result.incorrectQuestionIds.length > 0 && <Button className="secondary" onClick={() => { const practiceId = storePracticeSession(examId, result.incorrectQuestionIds); navigate(`/exams/${examId}/practice/${practiceId}`); }}>誤答だけを再演習</Button>}<Link className="button primary" to={`/exams/${examId}`}>試験ホームへ戻る</Link></div></section>;
}
