import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { gradeAnswer, type GradeResult } from "../core/scoring";
import type { PracticeMode } from "../core/practice";
import type { Attempt } from "../types/learning-data";
import type { ExamPackIndex, Question } from "../types/exam-pack";
import type { Domain } from "../schemas/exam-pack";
import { services } from "../services/app-services";
import { practiceSessionKey, storePracticeSession, type StoredPractice } from "../services/practice-session";
import { Markdown } from "../components/markdown";
import { Alert, Button, Loading, QuestionInput } from "../components/ui";

function formatAnswer(question: Question, values: readonly string[]): string {
  if (question.type === "input") return values.join(" / ");
  return values.map((value) => {
    const choice = question.choices.find((item) => item.id === value);
    return choice === undefined ? value : `${choice.id.toUpperCase()}. ${choice.text}`;
  }).join(" / ");
}

export function PracticeSetupPage() {
  const { examId = "" } = useParams(); const navigate = useNavigate(); const [mode, setMode] = useState<PracticeMode>("unanswered"); const [count, setCount] = useState(1); const [domains, setDomains] = useState<readonly Domain[]>([]); const [domainIds, setDomainIds] = useState<readonly string[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void services.catalog.load(examId).then((index) => setDomains(index.pack.domains)).catch(() => setError("試験データを読み込めません。")); }, [examId]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); const result = await services.createPractice(examId, { mode, count, ...(mode === "domain" ? { domainIds } : {}) }); setBusy(false); if (!result.ok) { setError(result.error.code === "no-candidates" ? "該当する問題がありません。" : result.error.code === "invalid-request" ? "演習条件を確認してください。" : `利用可能な問題は${result.error.availableCount ?? 0}問です。`); return; } const sessionId = storePracticeSession(examId, result.value.questionIds); navigate(`/exams/${examId}/practice/${sessionId}`); }
  return <section className="narrow"><Link className="back" to={`/exams/${examId}`}>← 試験ホーム</Link><p className="eyebrow">PRACTICE</p><h2>通常演習を設定</h2>{error && <Alert severity="error" title={error} />}<form className="panel form" onSubmit={(event) => void submit(event)}><label><span>演習モード</span><select value={mode} onChange={(event) => setMode(event.target.value as PracticeMode)}><option value="unanswered">未回答</option><option value="incorrect">誤答</option><option value="weakness">弱点</option><option value="bookmarked">お気に入り</option><option value="domain">分野別</option><option value="random">ランダム</option></select></label>{mode === "domain" && <fieldset><legend>対象分野</legend><div className="choice-list">{domains.map((domain) => <label className="choice" key={domain.id}><input type="checkbox" checked={domainIds.includes(domain.id)} onChange={(event) => setDomainIds(event.target.checked ? [...domainIds, domain.id] : domainIds.filter((id) => id !== domain.id))} /><span>{domain.name}</span></label>)}</div></fieldset>}<label><span>問題数</span><input type="number" min="1" step="1" value={count} onChange={(event) => setCount(event.target.valueAsNumber)} /></label><Button className="primary" busy={busy}>演習を始める</Button></form></section>;
}

export function PracticePage() {
  const { examId = "", sessionId = "" } = useParams(); const [index, setIndex] = useState<ExamPackIndex>(); const stored = useMemo<StoredPractice | undefined>(() => { const raw = sessionStorage.getItem(practiceSessionKey(sessionId)); return raw === null ? undefined : JSON.parse(raw) as StoredPractice; }, [sessionId]);
  const [position, setPosition] = useState(0); const [answer, setAnswer] = useState<readonly string[]>([]); const [attempt, setAttempt] = useState<Attempt>(); const [grade, setGrade] = useState<GradeResult>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [bookmarked, setBookmarked] = useState(false);
  const questionId = stored?.questionIds[position];
  useEffect(() => { void services.catalog.load(examId).then(setIndex); }, [examId]);
  useEffect(() => { if (questionId === undefined) return; void services.repository.listBookmarks(examId).then((rows) => setBookmarked(rows.some((row) => row.questionId === questionId))); }, [examId, questionId]);
  useEffect(() => { if (performance.getEntriesByName("practice-next-start", "mark").length === 0) return; performance.clearMeasures("practice-next-render"); performance.measure("practice-next-render", "practice-next-start"); performance.clearMarks("practice-next-start"); }, [position]);
  if (stored === undefined) return <Alert severity="error" title="演習情報がありません"><Link to={`/exams/${examId}/practice/setup`}>演習設定へ戻る</Link></Alert>;
  if (index === undefined) return <Loading />; const question = questionId === undefined ? undefined : index.questionById.get(questionId); if (question === undefined) return <Alert severity="error" title="問題を読み込めません" />; const activeQuestion = question; const activeStored = stored;
  async function submit() { setBusy(true); setError(""); try { const saved = await services.savePracticeAnswer(activeQuestion, sessionId, answer, Math.max(0, Date.now() - activeStored.startedAt)); setAttempt(saved); setGrade(gradeAnswer(activeQuestion, saved.selectedAnswer)); } catch { setError("回答を保存できませんでした。入力を保持しています。"); } finally { setBusy(false); } }
  function move(next: number) { if (next > position) performance.mark("practice-next-start"); setPosition(next); setAnswer([]); setAttempt(undefined); setGrade(undefined); setError(""); }
  return <section><div className="question-header"><span>問題 {position + 1} / {stored.questionIds.length}</span><Button className="ghost" onClick={() => { void services.repository.setBookmark(examId, question.id, !bookmarked).then(() => setBookmarked(!bookmarked)); }}>{bookmarked ? "★ お気に入り" : "☆ お気に入り"}</Button></div><article className="question-layout"><div className="panel"><p className="eyebrow">{question.domainId} · 難易度 {question.difficulty}</p><Markdown>{question.question}</Markdown><QuestionInput question={question} value={answer} disabled={attempt !== undefined || busy} onChange={setAnswer} />{error && <Alert severity="error" title={error} />}<Button className="primary" busy={busy} disabled={answer.length === 0 || (question.type === "input" && !answer[0]?.trim()) || attempt !== undefined} onClick={() => void submit()}>回答を確定</Button></div>{attempt !== undefined && grade !== undefined && <aside className="panel explanation"><Alert severity={grade.isCorrect ? "success" : "error"} title={grade.isCorrect ? "✓ 正解です" : "✕ 不正解です"} /><h3>回答内容</h3><dl className="answer-summary"><div><dt>正解</dt><dd>{formatAnswer(question, question.answers)}</dd></div><div><dt>自分の回答</dt><dd>{formatAnswer(question, attempt.selectedAnswer)}</dd></div></dl><h3>解説</h3><Markdown>{question.explanation}</Markdown>{question.type !== "input" && question.choices.map((choice) => <section key={choice.id}><h4>{choice.id.toUpperCase()}. {choice.text}</h4><Markdown>{question.choiceExplanations[choice.id] ?? ""}</Markdown></section>)}<h3>参照資料</h3><ul>{question.sources.map((source) => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">公式資料</a></li>)}</ul><label><span>理解度</span><select defaultValue="" onChange={(event) => { const value = Number(event.target.value) as 1 | 2 | 3 | 4; void services.repository.updateConfidence(attempt.id, value); }}><option value="" disabled>選択してください</option><option value="1">1 分からない</option><option value="2">2 あやふや</option><option value="3">3 理解した</option><option value="4">4 十分理解</option></select></label></aside>}</article><nav className="pager"><Button disabled={position === 0} onClick={() => move(position - 1)}>前の問題</Button>{position + 1 < stored.questionIds.length ? <Button disabled={attempt === undefined} onClick={() => move(position + 1)}>次の問題</Button> : <Link className="button primary" to={`/exams/${examId}`}>演習を終了</Link>}</nav></section>;
}
